#!/bin/tcsh -f
echo $1
sdcc  --model-large -I /home/dinesha/download/sdcc/device/include/mcs51 -I /home/dinesha/download/sdcc/device/include/  -L /home/dinesha/download/sdcc/device/lib/build/large -c $1.c
sdcc  --model-large -I /home/dinesha/download/sdcc/device/include/mcs51 -I /home/dinesha/download/sdcc/device/include/  -L /home/dinesha/download/sdcc/device/lib/build/large --code-loc 0x10 --data-loc 0x30 --stack-loc 0x20 --xram-loc 0x0000 $1.rel
packihx $1.ihx > $1.hex
